[versions]
agp = "8.9.1"
kotlin = "2.0.0"
core-ktx = "1.16.0"
junit = "4.13.2"
junit-version = "1.2.1"
espresso-core = "3.6.1"
lifecycle-runtime-ktx = "2.8.7"
activity-compose = "1.10.1"
appcompat = "1.7.0"
ktor = "3.1.0"
compose = "1.7.8"
compose-material3 = "1.3.2"
coil = "2.7.0"
hilt = "2.52"
hilt-compose = "1.2.0"
serialization = "1.8.0"
preferences-datastore = "1.1.4"
voyager = "1.1.0-beta03"
apollo = "4.0.0"
lottie = "6.6.0"
firebase-auth = "23.2.0"
firebase-gms-play-services = "21.3.0"
google-services = "4.4.2"
firebase-bom = "33.12.0"
firestore = "25.1.3"
firebase-storage = "21.0.1"
firebase-messaging = "24.1.1"
firebase-crashlytics = "19.4.2"
firebase-analytics = "22.4.0"
coroutines = "1.10.1"
compose-bom = "2025.04.00"
vico = "1.6.5"
poi = "5.2.4"
core-splashscreen = "1.0.1"
compose-material-icons = "1.7.8"
fig = "0.0.3"
palette = "1.0.0"
firebase-crashlytics-plugin = "3.0.3"
compose-compiler = "1.5.11"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

# Compose
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material-icons" }

# Hilt
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-kapt = { module = 'com.google.dagger:hilt-android-compiler', version.ref = "hilt" }
hilt-compose-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose" }


# Preferences Datastore
preferences-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "preferences-datastore" }

# Voyager
voyager-navigator = { group = "cafe.adriel.voyager", name = "voyager-navigator", version.ref = "voyager" }
voyager-animation = { group = "cafe.adriel.voyager", name = "voyager-transitions", version.ref = "voyager" }
voyager-tab = { group = "cafe.adriel.voyager", name = "voyager-tab-navigator", version.ref = "voyager" }

# Lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

# Firebase
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebase-auth" }
firebase-gms-play-services = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "firebase-gms-play-services" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebase-storage" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }

# Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }


# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

# Others
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
apache-poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi" }
apache-poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }
fig = { group = "com.github.theapache64", name = "fig", version.ref = "fig" }


# Plugin Libraries
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
google-services-plugin = { group = "com.google.gms", name = "google-services", version.ref = "google-services" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-compiler = { id = "androidx.compose.compiler", version.ref = "compose-compiler" }
dagger = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
[bundles]
compose = ["compose-material3", "compose-ui", "compose-ui-graphics", "compose-ui-tooling", "compose-ui-tooling-preview", "compose-runtime"]
ktor = ["ktor-client-core", "ktor-client-content-negotiation", "ktor-client-cio", "ktor-client-logging", "ktor-serialization-kotlinx-json"]
serialization = ["kotlinx-serialization-json", "kotlinx-serialization-core"]
voyager = ["voyager-navigator", "voyager-animation", "voyager-tab"]
firebase = ["firebase-auth", "firebase-gms-play-services", "firebase-firestore", "firebase-storage", "firebase-messaging", "firebase-crashlytics", "firebase-analytics"]
test = ["junit", "androidx-junit", "androidx-espresso-core"]