object Versions {
    const val agp = "8.5.2"
    const val kotlin = "1.9.22"
    const val coreKtx = "1.13.1"
    const val junit = "4.13.2"
    const val junitVersion = "1.2.1"
    const val espressoCore = "3.6.1"
    const val lifecycleRuntimeKtx = "2.8.6"
    const val activityCompose = "1.9.2"
    const val appcompat = "1.7.0"
    const val ktor = "2.3.2"
    const val compose = "1.5.4"
    const val composeMaterial3 = "1.1.2"
    const val coil = "2.7.0"
    const val hilt = "2.50"
    const val serialization = "1.5.1"
    const val room = "2.6.1"
    const val preferencesDatastore = "1.1.1"
    const val voyagerVersion = "1.1.0-beta02"
    const val apollo = "4.0.0"
    const val lottie = "6.5.2"
    const val firebaseAuth = "23.0.0"
    const val firebaseGmsPlayServices = "21.2.0"
    const val googleServices = "4.3.14"

}